"""increasing character limit on password to accomodate hashed pass size

Revision ID: 682cc0c8ddd4
Revises: 9f8f26451e17
Create Date: 2024-07-24 09:24:27.697503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682cc0c8ddd4'
down_revision = '9f8f26451e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
