"""Modifying the user_id in Track model

Revision ID: aaa932c36866
Revises: caa55fa47446
Create Date: 2024-07-12 20:28:58.888011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa932c36866'
down_revision = 'caa55fa47446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=80),
                              existing_nullable=True)
        batch_op.drop_constraint('fk_track_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_track_user_username', 'user', ['user_id'], [
                                    'username'])  # Add a name for the foreign key

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        # Use the same name here
        batch_op.drop_constraint('fk_track_user_username', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_track_user', 'user', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
                              existing_type=sa.String(length=80),
                              type_=sa.INTEGER(),
                              existing_nullable=True)

    # ### end Alembic commands ###
